# Generated by Django 3.2.4 on 2021-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0003_auto_20210610_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=' ', upload_to='Image/'),
            preserve_default=False,
        ),
    ]
