# Generated by Django 3.2.4 on 2021-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='descrip',
            field=models.CharField(default='', max_length=20, verbose_name='Описание фирм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firm',
            name='img',
            field=models.ImageField(default='', upload_to='Image/', verbose_name='Изображения фирм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firm',
            name='place',
            field=models.CharField(default='', max_length=20, verbose_name='Расположение фирм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='', upload_to='Profile/'),
            preserve_default=False,
        ),
    ]
