# Generated by Django 3.2.4 on 2021-06-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0007_auto_20210612_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='place',
        ),
    ]
