# Generated by Django 3.2.4 on 2021-06-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0009_auto_20210612_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='place',
        ),
    ]
