# Generated by Django 3.2.4 on 2021-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0010_remove_firm_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='place',
            field=models.CharField(default='Нет информации о местоположении', max_length=20, verbose_name='Расположение фирм'),
            preserve_default=False,
        ),
    ]
