# Generated by Django 3.2.4 on 2021-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0011_firm_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='categor',
            field=models.ManyToManyField(to='View.Category', verbose_name='Категории производства'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='descrip',
            field=models.CharField(max_length=200, verbose_name='Описание фирм'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='place',
            field=models.CharField(max_length=50, verbose_name='Расположение фирм'),
        ),
    ]
